# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3.1'
services:
  application:
    build: acm-back-end
    container_name: acm-back-end
    volumes:
      - "./acm-back-end:/var/www"
    depends_on:
      - database
    links:
      - database

  client:
    build: acm-front-end
    container_name: acm-front-end
    ports:
        - 4200:4200
    volumes:
        - ${FRONT_END}:/home/node/app/frontend
    tty: true
    command:
        - /bin/sh
        - -c
        - |
            cd /home/node/app/frontend && npm start
    expose:
        - "4200"
    links:
      - nginx-back

  database:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx-front:
    image: nginx
    container_name: nginx-front
    ports:
      - 8080:8080
    links:
      - client
      - nginx-back
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/angular.conf:/etc/nginx/conf.d/default.conf

  nginx-back:
    image: nginx
    container_name: nginx-back
    ports:
      - 8000:8000
    links:
      - application
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/symfony.conf:/etc/nginx/conf.d/default.conf