vich_uploader:
    db_driver: orm

    mappings:
        charged_fees:
            uri_prefix: /charged_fees
            upload_destination: '%kernel.project_dir%/public/charged_fees'
            namer: Vich\UploaderBundle\Naming\OrignameNamer